version: 1.2
workflows:
  - name:  cnn-variant-filter
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/cnn-variant-filter.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - develop
        - master
  - name:  RNA_aggregate
    subclass: WDL
    publish: True
    primaryDescriptorPath: /RNA_pipeline/RNA_aggregate.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - develop
        - master
  - name:  RNA_pipeline
    subclass: WDL
    publish: True
    primaryDescriptorPath: /RNA_pipeline/RNA_pipeline.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - develop
        - master
  - name:  WGS_pipeline
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/WGS_pipeline.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - develop
        - master
  - name:  WGS_aggregate
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/WGS_aggregate.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - develop
        - master
  - name:  rnaseq_mutect2_tumor_only
    subclass: WDL
    publish: True
    primaryDescriptorPath: /RNA_pipeline/rnaseq_mutect2_tumor_only.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - develop
        - master
 - name:  rsem_depmap
    subclass: WDL
    publish: True
    primaryDescriptorPath: /RNA_pipeline/rsem_depmap.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - develop
        - master
        - rsem_confidence_interval_calculation
