version: 1.2
workflows:
  - name: cnn-variant-filter
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/cnn-variant-filter.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
  - name: RNA_aggregate
    subclass: WDL
    publish: True
    primaryDescriptorPath: /RNA_pipeline/RNA_aggregate.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
  - name: RNA_pipeline
    subclass: WDL
    publish: True
    primaryDescriptorPath: /RNA_pipeline/RNA_pipeline.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
  - name: WGS_pipeline
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/WGS_pipeline.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - giab-mut-calling
  - name: WGS_aggregate
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/WGS_aggregate.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
  - name: rnaseq_mutect2_tumor_only
    subclass: WDL
    publish: True
    primaryDescriptorPath: /RNA_pipeline/rnaseq_mutect2_tumor_only.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
  - name: rsem_depmap
    subclass: WDL
    publish: True
    primaryDescriptorPath: /RNA_pipeline/rsem_depmap.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - rsem_confidence_interval_calculation
  - name: opencravat
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/opencravat.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - finishing_mutation_pipeline
  - name: bcftools_setGT
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/bcftools.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - finishing_mutation_pipeline
  - name: fix_mutect2col
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/fix_mutect2col.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - finishing_mutation_pipeline
  - name: omics_mutect2
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/omics_mutect2.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - finishing_mutation_pipeline
  - name: manta_annot
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/manta_annot.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - finishing_mutation_pipeline
  - name: Manta_SomaticSV
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/Manta_SomaticSV.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - finishing_mutation_pipeline
  - name: fix_mutect2_clust
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/fix_mutect2_clust.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - finishing_mutation_pipeline
  - name: merge_mutect2_replicates
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/merge_mutect2_replicates.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - finishing_mutation_pipeline
  - name: filter_to_maf
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/filter_to_maf.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - finishing_mutation_pipeline
  - name: merge_and_upload
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/merge_and_upload.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - finishing_mutation_pipeline
  - name: omics_post_mutect2
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/omics_post_mutect2.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - finishing_mutation_pipeline
  - name: opencravat_dm
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/opencravat_dm.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - add-cosmic-to-oc
        - add-oncokb-to-oc
  - name: vcf_to_depmap
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/vcf_to_depmap.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - dev
        - master
        - mutation-annotation-eval
        - update-vcf-to-depmap
  - name: vcf2maf
    subclass: WDL
    publish: True
    primaryDescriptorPath: /sandbox/vcf2maf/vcf2maf.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - qq-vcf2maf-test
  - name: hgvs
    subclass: WDL
    publish: True
    primaryDescriptorPath: /sandbox/hgvs/hgvs.wdl
    testParameterFiles:
      - /sandbox/hgvs/test.json
    filters: # All tags, no branches
      branches:
        - dev-hgvs
  - name: telomere
    subclass: WDL
    publish: True
    primaryDescriptorPath: /sandbox/telomere/telomerehunter.wdl
    testParameterFiles:
      - /sandbox/telomere/test.json
    filters: # All tags, no branches
      branches:
        - devel-telomere
  - name: rsem_aggregate_results
    subclass: WDL
    publish: True
    primaryDescriptorPath: /RNA_pipeline/rsem_aggregate_results.wdl
    branches:
        - add-effective-length
        - master
  - name: annotate_variants
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/annotate_variants.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - merge-annotators
        - master
  - name: mask_variants
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WGS_pipeline/mask_variants.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - mask-repeats-and-segdups
  - name: longReadMapper
    subclass: WDL
    publish: True
    primaryDescriptorPath: /long-read-omics/longReadMapper.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - long-read-dev
  - name: longReadMapper
    subclass: WDL
    publish: True
    primaryDescriptorPath: /long-read-omics/generateIndexFiles.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - long-read-dev
  - name: longReadMapper
    subclass: WDL
    publish: True
    primaryDescriptorPath: /long-read-omics/longReadMapper.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - long-read-dev
 name: longReadMapper
    subclass: WDL
    publish: True
    primaryDescriptorPath: /long-read-omics/longReadMapper.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - long-read-dev
- name: longReadMapper
    subclass: WDL
    publish: True
    primaryDescriptorPath: /long-read-omics/longReadMapper.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - long-read-dev
- name: longReadMapper
    subclass: WDL
    publish: True
    primaryDescriptorPath: /long-read-omics/longReadMapper.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - long-read-dev
- name: longReadMapper
    subclass: WDL
    publish: True
    primaryDescriptorPath: /long-read-omics/longReadMapper.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - long-read-dev
 name: IsoQuantQuantify
    subclass: WDL
    publish: True
    primaryDescriptorPath: /long-read-omics/IsoQuantQuantify.wdl
    testParameterFiles:
      - /test.json
    filters: # All tags, no branches
      branches:
        - long-read-dev
