name: docker

on: [push]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update build id
        run: |
          echo "SHA=\"${{ github.sha }}\"" > depmapomics/build.py
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.DEPLOY_SVC_ACCT }}
      - name: build docker image
        run: bash build-docker-image.sh ${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
      - name: Push Docker image
        run: docker push ${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
