name: DepMap omics tests

on: [push]

jobs:
  LintAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Branch name
        run: echo ${GITHUB_REF##*/}
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==19.0.3
          python -m pip install git+https://github.com/broadinstitute/genepy.git@123783afccb66b142a9b940ad929af39274b9d5c
#      - name: Lint with flake8
#        run: |
#          pip install flake8
#          # stop the build if there are Python syntax errors or undefined names
#          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#      - name: Typecheck with mypy
#        run: |
#          pip install mypy
#          # stop the build if there are Python syntax errors or undefined names
#          mypy .
      - name: Test with pytest
        run: |
          pip install pytest
          python -m pytest tests/
