name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f temp-requirements.txt ]; then pip install -r temp-requirements.txt; fi
      - name: Run pylint
        run: |
          pylint depmap_omic
#      - name: Test with pytest
#        run: |
#          pytest
